# Generated by Django 3.2.7 on 2021-09-04 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0002_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=100)),
                ('image_description', models.TextField()),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('category', models.ManyToManyField(to='album.Category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='album.user')),
            ],
        ),
    ]
