# Generated by Django 3.2.7 on 2021-09-04 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0004_auto_20210904_1736'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='place',
            new_name='places',
        ),
    ]
