# Generated by Django 3.2.7 on 2021-09-04 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0006_alter_category_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='place',
            new_name='places',
        ),
    ]
