# Generated by Django 3.2.7 on 2021-09-04 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0007_rename_place_location_places'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
    ]
